name: Python application


on:
  schedule:
    - cron: 45 12 * * *

env:
  DEVOPS_DIR: HW

permissions:
  contents: read

jobs:
 ETL:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    
    - name: pip_selenium
      run: pip install selenium
      shell: sh
      
    - name: pip_pandas
      run: pip install pandas
      shell: sh
    
    - name: pip_openpyxl
      run: pip install openpyxl
      shell: sh
    
    - name: ETL
      run: python ETL.py
      shell: sh

